// Copyright 2018 David Sansome
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// This file has been modified from the original.
// The table is transcribed from `kReplacements` in ios/TKMKanaInput.m in
// https://github.com/davidsansome/tsurukame. The escapes are resolved to literal kana and
// the surrounding Objective-C is gone; the mappings themselves are unchanged. See NOTICE.

// A 290 entry data table, which is what it is. Splitting it to satisfy a length rule would
// put half the alphabet in one file and half in another for no reader's benefit.
// swiftlint:disable type_body_length

/// Every romaji spelling this converter accepts, and the kana it produces.
///
/// Not a transliteration scheme so much as a record of what people type. It carries
/// Hepburn (`shi`, `chi`, `tsu`, `fu`), Kunrei (`si`, `ti`, `tu`, `hu`), the wapuro
/// conventions an IME expects (`nn` for ん, `x` or `l` for a small kana, `-` for the
/// katakana long vowel), and a number of spellings that are simply what someone reaches for
/// under time pressure (`ca` for か, `ce` for け). Each of those was presumably added
/// because a real answer was marked wrong, which is the sort of knowledge worth carrying
/// across rather than rediscovering.
///
/// Everything here is hiragana. Katakana is produced by transforming the result, so the
/// table does not have to exist twice.
enum RomajiTable {
    /// The longest key, which is how far back a match may reach.
    static let longestKey = 4

    static let entries: [String: String] = [
        "-": "ー",
        "a": "あ",
        "ba": "ば",
        "be": "べ",
        "bi": "び",
        "bo": "ぼ",
        "bu": "ぶ",
        "bya": "びゃ",
        "bye": "びぇ",
        "byi": "びぃ",
        "byo": "びょ",
        "byu": "びゅ",
        "ca": "か",
        "ce": "け",
        "cha": "ちゃ",
        "che": "ちぇ",
        "chi": "ち",
        "cho": "ちょ",
        "chu": "ちゅ",
        "chya": "ちゃ",
        "chye": "ちぇ",
        "chyo": "ちょ",
        "chyu": "ちゅ",
        "ci": "き",
        "co": "こ",
        "cu": "く",
        "cya": "ちゃ",
        "cye": "ちぇ",
        "cyi": "ちぃ",
        "cyo": "ちょ",
        "cyu": "ちゅ",
        "da": "だ",
        "de": "で",
        "dha": "でゃ",
        "dhe": "でぇ",
        "dhi": "でぃ",
        "dho": "でょ",
        "dhu": "でゅ",
        "di": "ぢ",
        "do": "ど",
        "du": "づ",
        "dwa": "どぁ",
        "dwe": "どぇ",
        "dwi": "どぃ",
        "dwo": "どぉ",
        "dwu": "どぅ",
        "dya": "ぢゃ",
        "dye": "ぢぇ",
        "dyi": "ぢぃ",
        "dyo": "ぢょ",
        "dyu": "ぢゅ",
        "e": "え",
        "fa": "ふぁ",
        "fe": "ふぇ",
        "fi": "ふぃ",
        "fo": "ふぉ",
        "fu": "ふ",
        "fwa": "ふぁ",
        "fwe": "ふぇ",
        "fwi": "ふぃ",
        "fwo": "ふぉ",
        "fwu": "ふぅ",
        "fya": "ふゃ",
        "fye": "ふぇ",
        "fyi": "ふぃ",
        "fyo": "ふょ",
        "fyu": "ふゅ",
        "ga": "が",
        "ge": "げ",
        "gi": "ぎ",
        "go": "ご",
        "gu": "ぐ",
        "gwa": "ぐぁ",
        "gwe": "ぐぇ",
        "gwi": "ぐぃ",
        "gwo": "ぐぉ",
        "gwu": "ぐぅ",
        "gya": "ぎゃ",
        "gye": "ぎぇ",
        "gyi": "ぎぃ",
        "gyo": "ぎょ",
        "gyu": "ぎゅ",
        "ha": "は",
        "he": "へ",
        "hi": "ひ",
        "ho": "ほ",
        "hu": "ふ",
        "hya": "ひゃ",
        "hye": "ひぇ",
        "hyi": "ひぃ",
        "hyo": "ひょ",
        "hyu": "ひゅ",
        "i": "い",
        "ja": "じゃ",
        "je": "じぇ",
        "ji": "じ",
        "jo": "じょ",
        "ju": "じゅ",
        "jya": "じゃ",
        "jye": "じぇ",
        "jyi": "じぃ",
        "jyo": "じょ",
        "jyu": "じゅ",
        "ka": "か",
        "ke": "け",
        "ki": "き",
        "ko": "こ",
        "ku": "く",
        "kwa": "くぁ",
        "kya": "きゃ",
        "kye": "きぇ",
        "kyi": "きぃ",
        "kyo": "きょ",
        "kyu": "きゅ",
        "la": "ぁ",
        "lca": "ヵ",
        "lce": "ヶ",
        "le": "れ",
        "li": "り",
        "lka": "ヵ",
        "lke": "ヶ",
        "lo": "ろ",
        "ltsu": "っ",
        "ltu": "っ",
        "lu": "る",
        "lwe": "ゎ",
        "lya": "りゃ",
        "lye": "りぇ",
        "lyi": "りぃ",
        "lyo": "りょ",
        "lyu": "りゅ",
        "ma": "ま",
        "me": "め",
        "mi": "み",
        "mo": "も",
        "mu": "む",
        "mya": "みゃ",
        "mye": "みぇ",
        "myi": "みぃ",
        "myo": "みょ",
        "myu": "みゅ",
        "n ": "ん",
        "na": "な",
        "ne": "ね",
        "ni": "に",
        "nn": "ん",
        "no": "の",
        "nu": "ぬ",
        "nya": "にゃ",
        "nye": "にぇ",
        "nyi": "にぃ",
        "nyo": "にょ",
        "nyu": "にゅ",
        "o": "お",
        "pa": "ぱ",
        "pe": "ぺ",
        "pi": "ぴ",
        "po": "ぽ",
        "pu": "ぷ",
        "pya": "ぴゃ",
        "pye": "ぴぇ",
        "pyi": "ぴぃ",
        "pyo": "ぴょ",
        "pyu": "ぴゅ",
        "qa": "くぁ",
        "qe": "くぇ",
        "qi": "くぃ",
        "qo": "くぉ",
        "qwa": "くぁ",
        "qwe": "くぇ",
        "qwi": "くぃ",
        "qwo": "くぉ",
        "qwu": "くぅ",
        "qya": "くゃ",
        "qye": "くぇ",
        "qyi": "くぃ",
        "qyo": "くょ",
        "qyu": "くゅ",
        "ra": "ら",
        "re": "れ",
        "ri": "り",
        "ro": "ろ",
        "ru": "る",
        "rya": "りゃ",
        "rye": "りぇ",
        "ryi": "りぃ",
        "ryo": "りょ",
        "ryu": "りゅ",
        "sa": "さ",
        "se": "せ",
        "sha": "しゃ",
        "she": "しぇ",
        "shi": "し",
        "sho": "しょ",
        "shu": "しゅ",
        "shya": "しゃ",
        "shye": "しぇ",
        "shyo": "しょ",
        "shyu": "しゅ",
        "si": "し",
        "so": "そ",
        "su": "す",
        "swa": "すぁ",
        "swe": "すぇ",
        "swi": "すぃ",
        "swo": "すぉ",
        "swu": "すぅ",
        "sya": "しゃ",
        "sye": "しぇ",
        "syi": "しぃ",
        "syo": "しょ",
        "syu": "しゅ",
        "ta": "た",
        "te": "て",
        "tha": "てゃ",
        "the": "てぇ",
        "thi": "てぃ",
        "tho": "てょ",
        "thu": "てゅ",
        "ti": "ち",
        "to": "と",
        "tsa": "つぁ",
        "tse": "つぇ",
        "tsi": "つぃ",
        "tso": "つぉ",
        "tsu": "つ",
        "tu": "つ",
        "twa": "とぁ",
        "twe": "とぇ",
        "twi": "とぃ",
        "two": "とぉ",
        "twu": "とぅ",
        "tya": "ちゃ",
        "tye": "ちぇ",
        "tyi": "ちぃ",
        "tyo": "ちょ",
        "tyu": "ちゅ",
        "u": "う",
        "va": "ゔぁ",
        "ve": "ゔぇ",
        "vi": "ゔぃ",
        "vo": "ゔぉ",
        "vu": "ゔ",
        "vya": "ゔゃ",
        "vye": "ゔぇ",
        "vyi": "ゔぃ",
        "vyo": "ゔょ",
        "vyu": "ゔゅ",
        "wa": "わ",
        "we": "うぇ",
        "wha": "うぁ",
        "whe": "うぇ",
        "whi": "うぃ",
        "who": "うぉ",
        "whu": "う",
        "wi": "うぃ",
        "wo": "を",
        "wu": "う",
        "xa": "ぁ",
        "xca": "ヵ",
        "xce": "ヶ",
        "xe": "ぇ",
        "xi": "ぃ",
        "xka": "ヵ",
        "xke": "ヶ",
        "xn": "ん",
        "xo": "ぉ",
        "xtsu": "っ",
        "xtu": "っ",
        "xu": "ぅ",
        "xwa": "ゎ",
        "xya": "ゃ",
        "xye": "ぇ",
        "xyi": "ぃ",
        "xyo": "ょ",
        "xyu": "ゅ",
        "ya": "や",
        "ye": "いぇ",
        "yi": "い",
        "yo": "よ",
        "yu": "ゆ",
        "za": "ざ",
        "ze": "ぜ",
        "zi": "じ",
        "zo": "ぞ",
        "zu": "ず",
        "zya": "じゃ",
        "zye": "じぇ",
        "zyi": "じぃ",
        "zyo": "じょ",
        "zyu": "じゅ"
    ]
}
// swiftlint:enable type_body_length
