public import Foundation
public import KBCore

/// Read-only JMdict lookup: the policy over a `JMDictStorage`.
///
/// Prefers a full dictionary at `databaseURL` (built by `make dict` into Application
/// Support); falls back to the small curated seed bundled with this package so a fresh
/// checkout works out of the box; and degrades to a no-op store when neither is
/// available (lookups then return nothing and the caller shows "no entry").
///
/// Looks up entries by exact form match — kanji headword or kana reading. Callers can
/// feed the dictionary base form from OpenJTalk (so 食べました → 食べる) for accurate
/// inflection handling; surface fallback handles tokens with no morphological base.
///
/// Everything here is pure Swift: deinflection, the base-then-surface fallback, and
/// parsing a furigana segmentation string into spans. The database lives behind
/// `JMDictStorage`, which is what lets this package build where SQLite cannot.
public final class JMDictStore: Sendable {
    private let storage: any JMDictStorage

    /// The general initializer: any storage, including a fake in tests.
    public init(storage: any JMDictStorage, isUsingBundledSeed: Bool = false) {
        self.storage = storage
        self.isUsingBundledSeed = isUsingBundledSeed
    }

    #if canImport(GRDB)
    /// Opens the best available dictionary. `databaseURL` is the optional full-dictionary
    /// location (Application Support); when it is missing, or is there but does not carry the
    /// schema the queries need, the bundled seed is used.
    ///
    /// A malformed database is treated exactly like an absent one, deliberately. It used to
    /// open, report `isReady`, and then fail every lookup, which is the worst of the three
    /// outcomes: the caller offers the affordance and the person is told their word has no
    /// entry. Falling back to the seed is honest, and ``isUsingBundledSeed`` says so.
    public convenience init(databaseURL: URL? = nil) {
        if let resolved = Self.resolve(databaseURL: databaseURL) {
            let storage = SQLiteJMDictStorage(url: resolved)
            if storage.isReady {
                self.init(storage: storage, isUsingBundledSeed: resolved != databaseURL)
                return
            }
            // The full dictionary is unusable. Retry on the seed, unless that IS what just
            // failed, in which case there is nothing left to fall back to.
            if let seed = Self.bundledSeedURL, seed != resolved {
                self.init(storage: SQLiteJMDictStorage(url: seed), isUsingBundledSeed: true)
                return
            }
        }
        self.init(storage: SQLiteJMDictStorage(url: nil), isUsingBundledSeed: false)
    }
    #else
    /// No SQLite backend exists on this platform yet, so every lookup is empty. The
    /// initializer still takes a URL so callers do not need to be conditionalized.
    public convenience init(databaseURL: URL? = nil) {
        self.init(storage: EmptyJMDictStorage())
    }
    #endif

    /// Resolution order: the full dictionary at `databaseURL` when the app supplies one,
    /// then the curated seed bundled here.
    ///
    /// This package deliberately bundles no full dictionary — it is a ~65 MB blob, and a
    /// shared package can't carry it for every consumer. Real coverage is the app's job:
    /// point `databaseURL` at a copy built by `make dict`, at one bundled in the app
    /// target's own resources, or at a first-use download.
    private static func resolve(databaseURL: URL?) -> URL? {
        if let databaseURL, FileManager.default.fileExists(atPath: databaseURL.path) {
            return databaseURL
        }
        return bundledSeedURL
    }

    /// The small curated seed bundled with this package. Deterministic — tests pin to it so they
    /// don't depend on whichever full dictionary happens to be bundled.
    ///
    /// `Bundle.module` is the Apple path only. Its generated accessor traps rather than
    /// returning nil when there is no resource bundle, and an Android APK has none, so
    /// reaching it there aborts the process instead of falling through to "no seed". The
    /// non-trapping locator gives every other platform a real `nil`, which every caller here
    /// already handles. See `PackageResourceLocator`.
    /// NEITHER half names the enclosing PACKAGE. `Bundle.module` is generated by the compiler,
    /// and the off-Apple locator is keyed to the TARGET name, because this target is copied
    /// verbatim into a package called `KBKits`: a lookup spelled
    /// `KBDictionaryKit_KBDictionaryKit` would then find nothing there, with no compile error
    /// and no crash to say so. See
    /// `PackageResourceLocator.url(targetName:resource:extension:roots:)`.
    static var bundledSeedURL: URL? {
        #if canImport(Darwin)
        return Bundle.module.url(forResource: "jmdict-seed", withExtension: "sqlite")
        #else
        return PackageResourceLocator.url(targetName: "KBDictionaryKit",
                                          resource: "jmdict-seed", extension: "sqlite")
        #endif
    }

    /// Whether a dictionary opened successfully. TRUE FOR THE SEED TOO, so it answers
    /// "is there a database" and NOT "can this actually define a word" - see
    /// ``isUsingBundledSeed``.
    public var isReady: Bool { storage.isReady }

    /// Whether the opened dictionary is the bundled seed rather than a full JMdict.
    ///
    /// The seed holds a few dozen entries, so a caller that treats `isReady` as "lookup
    /// works" will offer a lookup affordance that misses on almost every word and reports
    /// it as a word with no entry, when the truth is a dictionary that was never
    /// installed. Callers should say which of those two it is.
    public let isUsingBundledSeed: Bool

    /// Look up dictionary entries by exact form (kanji or kana). Returns at most `limit`
    /// entries; empty when nothing matches.
    public func lookup(form: String, limit: Int = 8) -> [JMDictEntry] {
        storage.entries(matchingForm: form, limit: limit)
    }

    /// The English source word to gloss over a katakana loanword (e.g. コミュニケーション
    /// → "communication"), or nil when the form isn't a glossable English loanword
    /// (wasei-eigo, non-English loans, and native katakana are deliberately excluded by
    /// the build-time gate). Returns nil when the dictionary predates the gloss column.
    public func englishGloss(forKatakana form: String) -> String? {
        storage.englishGloss(forKatakana: form)
    }

    /// All kana forms of every entry listing `form` as a headword or variant — the lean
    /// path for the reading validator, which calls it per kanji token during reader builds.
    public func kanaReadings(forForm form: String) -> [String] {
        storage.kanaReadings(forForm: form)
    }

    /// Every kana reading the dictionary lists for a form BEGINNING WITH `form` - the prefix
    /// scan the "uncorroborated reading" gate is built on.
    ///
    /// `kanaReadings(forForm:)` asks whether the dictionary lists a reading for exactly this
    /// surface. This asks the wider and more useful question: does the ordinary dictionary
    /// account for this reading of this surface AT ALL, through any form the surface heads?
    /// 覗 read のぞ is accounted for by 覗く(のぞく) and 撫 read な by 撫でる(なでる), neither of
    /// which an exact lookup sees.
    ///
    /// That distinction is what separates a name from ordinary vocabulary without a
    /// proper-noun tag: 司波 read つかさなみ and 養源寺 read やしなえげんてら are kun
    /// concatenations the tokenizer assembled, and NO dictionary form accounts for them.
    ///
    /// `limit` bounds a short common prefix. Truncation is one-directional - it can only fail
    /// to corroborate - and failing to corroborate is the branch that ACTS, so the default sits
    /// above the measured worst case rather than at a round number: 大 heads 1,890 distinct
    /// readings in the shipping dictionary, and no other single kanji exceeds it.
    public func kanaReadings(forFormsStartingWith form: String, limit: Int = 4000) -> [String] {
        storage.kanaReadings(forKanjiFormsStartingWith: form, limit: limit)
    }

    /// Whether the ordinary dictionary can account for `reading` as a reading of `form`:
    /// some entry whose kanji form begins with `form` has a kana reading beginning with
    /// `reading`. Both sides are folded to hiragana first, so a katakana dictionary reading
    /// never false-negatives against our hiragana rendering.
    ///
    /// FALSE is the interesting answer: it means we rendered something no dictionary form
    /// supports, which is the signature of a kun concatenation over a name.
    public func corroborates(form: String, reading: String, limit: Int = 4000) -> Bool {
        guard !form.isEmpty, !reading.isEmpty else { return false }
        let ours = Self.hiragana(reading)
        return kanaReadings(forFormsStartingWith: form, limit: limit)
            .contains { Self.hiragana($0).hasPrefix(ours) }
    }

    /// Katakana folded to hiragana, so a dictionary reading and a rendered one compare on the
    /// same script. Long-vowel marks are left alone: they are a real spelling difference.
    static func hiragana(_ text: String) -> String {
        String(String.UnicodeScalarView(text.unicodeScalars.map { scalar in
            (0x30A1...0x30F6).contains(scalar.value)
                ? Unicode.Scalar(scalar.value - 0x60)! : scalar
        }))
    }

    /// Per-character furigana spans for the exact (form, reading) pair from the
    /// JmdictFurigana dataset, tiling the whole form (nil kana at okurigana positions).
    /// Exact-pair match only — a base form's reading must never transfer to a surface
    /// unchecked (来る=くる but 来た=きた). Empty when the pair is unknown, and degrades
    /// to empty (never errors) when the opened dictionary predates the `furigana` table.
    public func furiganaSegments(form: String, reading: String) -> [FuriganaSpan] {
        guard !form.isEmpty, !reading.isEmpty,
              let segmentation = storage.furiganaSegmentation(form: form, reading: reading)
        else { return [] }
        return JmdictFuriganaParser.spans(segmentation: segmentation, formLength: form.count) ?? []
    }

    /// Look up a (possibly inflected) surface: try the exact form first, then rule-based
    /// deinflection candidates (読んだ→読む, 食べました→食べる, 高かった→高い), returning the
    /// first candidate that hits the dictionary. Wrong guesses simply don't match, so this
    /// never returns worse results than a plain surface lookup.
    public func lookup(deinflecting surface: String, limit: Int = 8) -> [JMDictEntry] {
        let direct = lookup(form: surface, limit: limit)
        if !direct.isEmpty { return direct }
        for candidate in Deinflector.candidates(for: surface) {
            let hit = lookup(form: candidate, limit: limit)
            if !hit.isEmpty { return hit }
        }
        return []
    }

    /// Look up by base form first, then surface as a fallback (handles tokens with no
    /// morphological base — numbers, names, particles where surface == base anyway).
    public func lookup(base: String, surface: String) -> [JMDictEntry] {
        let primary = lookup(form: base)
        if !primary.isEmpty || base == surface { return primary }
        return lookup(form: surface)
    }
}
